// <auto-generated />
using BerthaApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BerthaApplication.Migrations
{
    [DbContext(typeof(BerthaContext))]
    [Migration("20181119131852_BerthaApplication.Models.BerthaContext")]
    partial class BerthaApplicationModelsBerthaContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BerthaApplication.Models.HealthRecords", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BodyTemperature");

                    b.Property<double>("CarbonMonoxide");

                    b.Property<double>("DiastolicPressure");

                    b.Property<double>("Dust");

                    b.Property<double>("Fluor");

                    b.Property<int>("HeartBeatPerSecond");

                    b.Property<string>("Location");

                    b.Property<double>("Nitrogen");

                    b.Property<double>("Ozone");

                    b.Property<string>("RecordTime");

                    b.Property<double>("Sulphur");

                    b.Property<double>("SystolicPressure");

                    b.Property<int>("UserId");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthRecord");
                });

            modelBuilder.Entity("BerthaApplication.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BerthaApplication.Models.HealthRecords", b =>
                {
                    b.HasOne("BerthaApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
